# Generated by Django 3.0.5 on 2020-04-22 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laterality', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=5, null=True)),
                ('level', models.CharField(choices=[('URETHRA', 'Urethra'), ('APEX', 'Apex'), ('MID', 'Mid'), ('BASE', 'Base'), ('SV', 'Seminal vesicles')], max_length=10)),
                ('zone', models.CharField(choices=[('PZa', 'PZ anterior'), ('PZpl', 'PZ posterolateral'), ('PZpm', 'PZ posteromedial'), ('CZ', 'CZ'), ('TZa', 'TZ anterior'), ('TZp', 'TZ posterior'), ('AFS', 'Anterior fibromuscular stroma'), ('URETHRA', 'Urethra'), ('SV', 'Seminal vesicles')], max_length=10)),
            ],
            options={
                'unique_together': {('laterality', 'level', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='MriEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mri_date', models.DateField()),
                ('psa_level', models.IntegerField()),
                ('ece', models.BooleanField()),
                ('svi', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MriLesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('adc', models.IntegerField()),
                ('score', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=2, verbose_name='PIRADS 2.1 score')),
                ('upgraded', models.CharField(choices=[('NO', 'No'), ('PZ DCE', 'Yes - PZ DCE'), ('TZ DWI', 'Yes - TZ DWI')], max_length=20, verbose_name='PIRADS 2.1 upgraded')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesions', to='api.MriEntry')),
                ('locations', models.ManyToManyField(to='api.Location')),
            ],
        ),
        migrations.AddField(
            model_name='mrientry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mri_entries', to='api.Patient'),
        ),
    ]
