# Generated by Django 3.0.5 on 2020-04-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MriEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mri_date', models.DateField(verbose_name='MRI date')),
                ('psa_level', models.IntegerField(verbose_name='PSA level')),
                ('ece', models.BooleanField(verbose_name='ECE')),
                ('svi', models.CharField(choices=[('NO', 'No'), ('LEFT', 'Yes - left'), ('RIGHT', 'Yes - right'), ('BILATERAL', 'Yes - bilateral')], max_length=20, verbose_name='SVI')),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='PathologyEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('procedure_date', models.DateField(verbose_name='Procedure date')),
                ('specimen_type', models.CharField(choices=[('BIOPSY', 'Biopsy'), ('PROSTATECTOMY', 'Prostatectomy')], max_length=20, verbose_name='Specimen type')),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PiradLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('l_base_cz', 'l_base_cz'), ('l_sv', 'l_sv'), ('l_apex_pza', 'l_apex_pza'), ('l_apex_pzpl', 'l_apex_pzpl'), ('l_apex_pzpm', 'l_apex_pzpm'), ('l_apex_tza', 'l_apex_tza'), ('l_apex_tzp', 'l_apex_tzp'), ('l_apex_afs', 'l_apex_afs'), ('l_mid_pza', 'l_mid_pza'), ('l_mid_pzpl', 'l_mid_pzpl'), ('l_mid_pzpm', 'l_mid_pzpm'), ('l_mid_tza', 'l_mid_tza'), ('l_mid_tzp', 'l_mid_tzp'), ('l_mid_afs', 'l_mid_afs'), ('l_base_pza', 'l_base_pza'), ('l_base_pzpl', 'l_base_pzpl'), ('l_base_pzpm', 'l_base_pzpm'), ('l_base_tza', 'l_base_tza'), ('l_base_tzp', 'l_base_tzp'), ('l_base_afs', 'l_base_afs'), ('r_base_cz', 'r_base_cz'), ('r_sv', 'r_sv'), ('r_apex_pza', 'r_apex_pza'), ('r_apex_pzpl', 'r_apex_pzpl'), ('r_apex_pzpm', 'r_apex_pzpm'), ('r_apex_tza', 'r_apex_tza'), ('r_apex_tzp', 'r_apex_tzp'), ('r_apex_afs', 'r_apex_afs'), ('r_mid_pza', 'r_mid_pza'), ('r_mid_pzpl', 'r_mid_pzpl'), ('r_mid_pzpm', 'r_mid_pzpm'), ('r_mid_tza', 'r_mid_tza'), ('r_mid_tzp', 'r_mid_tzp'), ('r_mid_afs', 'r_mid_afs'), ('r_base_pza', 'r_base_pza'), ('r_base_pzpl', 'r_base_pzpl'), ('r_base_pzpm', 'r_base_pzpm'), ('r_base_tza', 'r_base_tza'), ('r_base_tzp', 'r_base_tzp'), ('r_base_afs', 'r_base_afs'), ('urethra', 'urethra')], max_length=20, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='PsmaEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('psma_date', models.DateField(verbose_name='PSMA date')),
                ('comments', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psma_entries', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PsmaLesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_index', models.BooleanField(default=False, verbose_name='Index lesion?')),
                ('suv', models.IntegerField(verbose_name='SUV')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesions', to='api.PsmaEntry')),
                ('locations', models.ManyToManyField(to='api.PiradLocation')),
            ],
        ),
        migrations.CreateModel(
            name='PathologyLesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_index', models.BooleanField(default=False, verbose_name='Index lesion?')),
                ('grade', models.CharField(choices=[('ISUP 1', 'ISUP 1'), ('ISUP 2', 'ISUP 2'), ('ISUP 3', 'ISUP 3'), ('ISUP 4', 'ISUP 4'), ('ISUP 5', 'ISUP 5'), ('NONE', 'No malignancy')], max_length=10, verbose_name='Lesion grade')),
                ('greatest_percentage', models.IntegerField(null=True, verbose_name='Greatest percentage of cancer')),
                ('positive_core', models.IntegerField(null=True, verbose_name='Positive core number')),
                ('total_core', models.IntegerField(null=True, verbose_name='Total core number')),
                ('lesion_size', models.IntegerField(null=True, verbose_name='Lesion size')),
                ('loc_side', models.CharField(choices=[('RIGHT', 'Right'), ('LEFT', 'Left'), ('NA', 'Not stated')], max_length=10, verbose_name='Side of prostate')),
                ('loc_zone', models.CharField(choices=[('BASE', 'Base'), ('MID', 'Mid'), ('APEX', 'Apex'), ('NA', 'Not stated')], max_length=5, verbose_name='Zone of prostate')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesions', to='api.PathologyEntry')),
            ],
        ),
        migrations.AddField(
            model_name='pathologyentry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathology_entries', to='api.Patient'),
        ),
        migrations.CreateModel(
            name='MriLesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_index', models.BooleanField(verbose_name='Index lesion?')),
                ('size', models.IntegerField()),
                ('adc', models.IntegerField(verbose_name='ADC')),
                ('score', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=2, verbose_name='PIRADS 2.1 score')),
                ('upgraded', models.CharField(choices=[('NO', 'No'), ('PZ DCE', 'Yes - PZ DCE'), ('TZ DWI', 'Yes - TZ DWI')], max_length=20, verbose_name='PIRADS 2.1 upgraded')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesions', to='api.MriEntry')),
                ('locations', models.ManyToManyField(to='api.PiradLocation')),
            ],
        ),
        migrations.AddField(
            model_name='mrientry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mri_entries', to='api.Patient'),
        ),
    ]
