# Generated by Django 3.0.5 on 2020-04-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.CharField(max_length=50, verbose_name='patient ID')),
                ('mri_date', models.DateField()),
                ('psa_level', models.IntegerField()),
                ('ece', models.BooleanField()),
                ('svi', models.CharField(max_length=20)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laterality', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5, null=True)),
                ('level', models.CharField(choices=[('URETHRA', 'Urethra'), ('APEX', 'Apex'), ('MID', 'Mid'), ('BASE', 'Base'), ('SV', 'Seminal vesicles')], max_length=10)),
                ('zone', models.CharField(choices=[('PZa', 'PZ anterior'), ('PZpl', 'PZ posterolateral'), ('PZpm', 'PZ posteromedial'), ('CZ', 'CZ'), ('TZa', 'TZ anterior'), ('TZp', 'TZ posterior'), ('AFS', 'Anterior fibromuscular stroma'), ('URETHRA', 'Urethra'), ('SV', 'Seminal vesicles')], max_length=10)),
            ],
            options={
                'unique_together': {('laterality', 'level', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IND', 'Index lesion'), ('ADD', 'Additional lesion')], max_length=10)),
                ('size', models.IntegerField()),
                ('adc', models.IntegerField()),
                ('score', models.CharField(max_length=5, verbose_name='PIRADS 2.1 score')),
                ('upgraded', models.CharField(max_length=20, verbose_name='PIRADS 2.1 upgraded')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesions', to='api.Entry')),
                ('locations', models.ManyToManyField(to='api.Location')),
            ],
        ),
    ]
