# Generated by Django 3.0.5 on 2020-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrientry',
            name='psa_level',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PSA level'),
        ),
        migrations.AlterField(
            model_name='mrilesion',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pathologylesion',
            name='greatest_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Greatest percentage of cancer'),
        ),
        migrations.AlterField(
            model_name='pathologylesion',
            name='lesion_size',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Lesion size'),
        ),
        migrations.AlterField(
            model_name='psmalesion',
            name='suv',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='SUV'),
        ),
    ]
