# Generated by Django 3.0.5 on 2020-04-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrientry',
            name='ece',
            field=models.BooleanField(verbose_name='ECE'),
        ),
        migrations.AlterField(
            model_name='mrientry',
            name='mri_date',
            field=models.DateField(verbose_name='MRI Date'),
        ),
        migrations.AlterField(
            model_name='mrientry',
            name='psa_level',
            field=models.IntegerField(verbose_name='PSA Level'),
        ),
        migrations.AlterField(
            model_name='mrientry',
            name='svi',
            field=models.CharField(max_length=20, verbose_name='SVI'),
        ),
        migrations.AlterField(
            model_name='mrilesion',
            name='adc',
            field=models.IntegerField(verbose_name='ADC'),
        ),
    ]
