# Generated by Django 3.0.5 on 2020-04-12 06:16

from django.db import migrations

from ..models import Location as LocationModel


def generate_locations(apps, schema_editor):
    objects = []
    laterality = ("L", "R")
    levels = LocationModel.level_choices
    zones = LocationModel.zone_choices

    Location = apps.get_model("api", "Location")
    for lat in laterality:
        objects.append(Location(laterality=lat, level="BASE", zone="CZ"))
        objects.append(Location(laterality=lat, level="SV", zone="SV"))
        for (lvl, _) in levels:
            if lvl in ("SV", "URETHRA"):
                continue
            for (z, _) in zones:
                if z in ("SV", "URETHRA", "CZ"):
                    continue
                location = Location(laterality=lat, level=lvl, zone=z,)
                objects.append(location)
    objects.append(Location(level="URETHRA", zone="URETHRA"))
    Location.objects.bulk_create(objects)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200412_0541"),
    ]

    operations = [migrations.RunPython(generate_locations)]


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_locations)
    ]
