# Generated by Django 3.0.5 on 2020-04-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200412_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesion',
            name='score',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=2, verbose_name='PIRADS 2.1 score'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='upgraded',
            field=models.CharField(choices=[('NO', 'No'), ('PZ DCE', 'Yes - PZ DCE'), ('TZ DWI', 'Yes - TZ DWI')], max_length=20, verbose_name='PIRADS 2.1 upgraded'),
        ),
    ]
