# Generated by Django 3.0.5 on 2020-04-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200430_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrientry',
            name='psa_level',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='PSA level'),
        ),
        migrations.AlterField(
            model_name='mrilesion',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pathologylesion',
            name='greatest_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Greatest percentage of cancer'),
        ),
    ]
