# Generated by Django 3.0.5 on 2020-05-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200430_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mrientry',
            options={'verbose_name_plural': 'MRI entries'},
        ),
        migrations.AlterModelOptions(
            name='pathologyentry',
            options={'verbose_name_plural': 'Pathology entries'},
        ),
        migrations.AlterModelOptions(
            name='psmaentry',
            options={'verbose_name_plural': 'PSMA entries'},
        ),
    ]
