# Generated by Django 3.0.5 on 2020-04-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200412_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesion',
            name='name',
            field=models.CharField(choices=[('index', 'Index lesion'), ('additional', 'Additional lesion')], max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='laterality',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=5, null=True),
        ),
    ]
