# Generated by Django 3.0.5 on 2020-06-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_duplicated_locations_20200621_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piradlocation',
            name='label',
            field=models.CharField(choices=[('l_base_cz', 'l_base_cz'), ('l_sv', 'l_sv'), ('l_apex_pza', 'l_apex_pza'), ('l_apex_pzpl', 'l_apex_pzpl'), ('l_apex_pzpm', 'l_apex_pzpm'), ('l_apex_tza', 'l_apex_tza'), ('l_apex_tzp', 'l_apex_tzp'), ('l_apex_afs', 'l_apex_afs'), ('l_mid_pza', 'l_mid_pza'), ('l_mid_pzpl', 'l_mid_pzpl'), ('l_mid_pzpm', 'l_mid_pzpm'), ('l_mid_tza', 'l_mid_tza'), ('l_mid_tzp', 'l_mid_tzp'), ('l_mid_afs', 'l_mid_afs'), ('l_base_pza', 'l_base_pza'), ('l_base_pzpl', 'l_base_pzpl'), ('l_base_pzpm', 'l_base_pzpm'), ('l_base_tza', 'l_base_tza'), ('l_base_tzp', 'l_base_tzp'), ('l_base_afs', 'l_base_afs'), ('r_base_cz', 'r_base_cz'), ('r_sv', 'r_sv'), ('r_apex_pza', 'r_apex_pza'), ('r_apex_pzpl', 'r_apex_pzpl'), ('r_apex_pzpm', 'r_apex_pzpm'), ('r_apex_tza', 'r_apex_tza'), ('r_apex_tzp', 'r_apex_tzp'), ('r_apex_afs', 'r_apex_afs'), ('r_mid_pza', 'r_mid_pza'), ('r_mid_pzpl', 'r_mid_pzpl'), ('r_mid_pzpm', 'r_mid_pzpm'), ('r_mid_tza', 'r_mid_tza'), ('r_mid_tzp', 'r_mid_tzp'), ('r_mid_afs', 'r_mid_afs'), ('r_base_pza', 'r_base_pza'), ('r_base_pzpl', 'r_base_pzpl'), ('r_base_pzpm', 'r_base_pzpm'), ('r_base_tza', 'r_base_tza'), ('r_base_tzp', 'r_base_tzp'), ('r_base_afs', 'r_base_afs'), ('urethra', 'urethra')], max_length=20, unique=True, verbose_name='Location'),
        ),
    ]
