# Generated by Django 3.0.5 on 2020-04-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200413_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesion',
            name='name',
        ),
    ]
